import React from 'react';

const Dashboard = () => {
  return (
    <div className="max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-4 gap-6">
      {/* Sidebar */}
      <div className="lg:col-span-1 bg-gray-800 rounded-lg p-4">
        <h3 className="text-xl font-semibold mb-4">Analysis Reports</h3>
        <button 
          onClick={() => console.log('View overall analysis')}
          className="w-full bg-blue-600 hover:bg-blue-700 py-2 rounded mb-4"
        >
          Overall Solution Analysis
        </button>
        
        <h4 className="font-medium mb-3">Target Subindustries</h4>
        <div className="bg-gray-700 rounded p-2 mb-2">
          <p>Technology - Software Development</p>
        </div>
        <div className="bg-gray-700 rounded p-2 mb-2">
          <p>Healthcare - Electronic Health Records</p>
        </div>
      </div>

      {/* Main Content Area */}
      <div className="lg:col-span-3 bg-gray-800 rounded-lg p-6">
        <h3 className="text-2xl font-semibold mb-4">Market Intelligence Report</h3>
        <div className="prose prose-invert max-w-none">
          <h4 className="text-xl font-semibold">Executive Summary</h4>
          <p>This is the comprehensive solution analysis generated by our AI system.</p>
          
          <h4 className="text-xl font-semibold mt-6">Key Findings</h4>
          <ul className="list-disc pl-6 space-y-2">
            <li>The solution demonstrates strong alignment with industry requirements</li>
            <li>Significant competitive advantage in the targeted segments</li>
            <li>Potential for 25%+ market share increase in the next 18 months</li>
          </ul>
          
          <h4 className="text-xl font-semibold mt-6">Recommendations</h4>
          <ol className="list-decimal pl-6 space-y-2">
            <li>Focus on high-growth subindustries identified in the analysis</li>
            <li>Develop targeted messaging for key buyer personas</li>
            <li>Implement the recommended go-to-market strategies</li>
          </ol>
        </div>
      </div>
    </div>
  );
};

export default Dashboard;